import { useEffect, useState } from "react";
import { formatMealFromMealDB } from "../../helpers/inYourFridge";
import { get10RandomMeals } from "../../services/theMealDB";

const Recipes = () => {
  const [randomMeals, setRandomMeals] = useState([
    {
      idMeal: "52838",
      strMeal: "Venetian Duck Ragu",
      strDrinkAlternate: null,
      strCategory: "Pasta",
      strArea: "Italian",
      strInstructions:
        "Heat the oil in a large pan. Add the duck legs and brown on all sides for about 10 mins. Remove to a plate and set aside. Add the onions to the pan and cook for 5 mins until softened. Add the garlic and cook for a further 1 min, then stir in the cinnamon and flour and cook for a further min. Return the duck to the pan, add the wine, tomatoes, stock, herbs, sugar and seasoning. Bring to a simmer, then lower the heat, cover with a lid and cook for 2 hrs, stirring every now and then.\r\nCarefully lift the duck legs out of the sauce and place on a plate – they will be very tender so try not to lose any of the meat. Pull off and discard the fat, then shred the meat with 2 forks and discard the bones. Add the meat back to the sauce with the milk and simmer, uncovered, for a further 10-15 mins while you cook the pasta.\r\nCook the pasta following pack instructions, then drain, reserving a cup of the pasta water, and add the pasta to the ragu. Stir to coat all the pasta in the sauce and cook for 1 min more, adding a splash of cooking liquid if it looks dry. Serve with grated Parmesan, if you like.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/qvrwpt1511181864.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=oWQDVgjB_Lw",
      strIngredient1: "Olive Oil",
      strIngredient2: "Duck Legs",
      strIngredient3: "Onions",
      strIngredient4: "Garlic",
      strIngredient5: "Cinnamon",
      strIngredient6: "Plain Flour",
      strIngredient7: "Red Wine",
      strIngredient8: "Chopped Tomatoes",
      strIngredient9: "Chicken Stock Cube",
      strIngredient10: "Rosemary",
      strIngredient11: "Bay Leaves",
      strIngredient12: "Sugar",
      strIngredient13: "Milk",
      strIngredient14: "Paccheri Pasta",
      strIngredient15: "Parmesan Cheese",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 tbls",
      strMeasure2: "4",
      strMeasure3: "2 finely chopped",
      strMeasure4: "2 cloves minced",
      strMeasure5: "2 tsp ground",
      strMeasure6: "2 tsp",
      strMeasure7: "250ml",
      strMeasure8: "800g",
      strMeasure9: "1",
      strMeasure10: "3 sprigs",
      strMeasure11: "2",
      strMeasure12: "1 tsp ",
      strMeasure13: "2 tbs",
      strMeasure14: "600g",
      strMeasure15: "Grated",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/venetian-duck-ragu",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "53026",
      strMeal: "Tamiya",
      strDrinkAlternate: null,
      strCategory: "Vegetarian",
      strArea: "Egyptian",
      strInstructions:
        "oak the beans in water to cover overnight.Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder.If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 minutes.\r\nShape the bean mixture into 1-inch balls.Flatten slightly and coat with flour.\r\nHeat at least 1½-inches of oil over medium heat to 365 degrees.\r\nFry the patties in batches, turning once, until golden brown on all sides, about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=mulqW-J3Yy4",
      strIngredient1: "Broad Beans",
      strIngredient2: "Spring Onions",
      strIngredient3: "Garlic Clove",
      strIngredient4: "Parsley",
      strIngredient5: "Cumin",
      strIngredient6: "Baking Powder",
      strIngredient7: "Cayenne Pepper",
      strIngredient8: "Flour",
      strIngredient9: "Vegetable Oil",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "3 cups ",
      strMeasure2: "6",
      strMeasure3: "4",
      strMeasure4: "1/4 cup",
      strMeasure5: "2 tsp",
      strMeasure6: "1 tsp ",
      strMeasure7: "1/2 tsp",
      strMeasure8: "Spinkling",
      strMeasure9: "As required",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52883",
      strMeal: "Sticky Toffee Pudding",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "British",
      strInstructions:
        "Preheat the oven to 180C/160C Fan/Gas 4. Butter a wide shallow 1.7-litre/3-pint ovenproof dish.\r\nPut the butter, sugar, eggs, flour, baking powder, bicarbonate of soda and treacle into a mixing bowl. Beat using an electric handheld whisk for about 30 seconds or until combined. Pour in the milk gradually and whisk again until smooth. Pour into the prepared dish. Bake for 35–40 minutes or until well risen and springy in the centre.\r\nTo make the sauce, put all the ingredients into a saucepan and stir over a low heat until the sugar has dissolved and the butter has melted. Bring to the boil, stirring for a minute.\r\nTo serve, pour half the sauce over the pudding in the baking dish. Serve with the cream or ice cream.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/xqqqtu1511637379.jpg",
      strTags: "Pudding,Cake,Desert",
      strYoutube: "https://www.youtube.com/watch?v=Wytv3bjqJII",
      strIngredient1: "Butter",
      strIngredient2: "Muscovado Sugar",
      strIngredient3: "Eggs",
      strIngredient4: "Self-raising Flour",
      strIngredient5: "Baking Powder",
      strIngredient6: "Bicarbonate Of Soda",
      strIngredient7: "Black Treacle",
      strIngredient8: "Milk",
      strIngredient9: "Double Cream",
      strIngredient10: "Butter",
      strIngredient11: "Muscovado Sugar",
      strIngredient12: "Black Treacle",
      strIngredient13: "Double Cream",
      strIngredient14: "Vanilla Extract",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "100g ",
      strMeasure2: "175g",
      strMeasure3: "2 large",
      strMeasure4: "225g",
      strMeasure5: "1 tsp ",
      strMeasure6: "1 tsp ",
      strMeasure7: "3 tbs",
      strMeasure8: "275ml",
      strMeasure9: "to serve",
      strMeasure10: "100g ",
      strMeasure11: "125g",
      strMeasure12: "1 tbs",
      strMeasure13: "300ml ",
      strMeasure14: "1 tsp ",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbc.co.uk/food/recipes/marys_sticky_toffee_41970",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52772",
      strMeal: "Teriyaki Chicken Casserole",
      strDrinkAlternate: null,
      strCategory: "Chicken",
      strArea: "Japanese",
      strInstructions:
        "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
      strTags: "Meat,Casserole",
      strYoutube: "https://www.youtube.com/watch?v=4aZr5hZXP_s",
      strIngredient1: "soy sauce",
      strIngredient2: "water",
      strIngredient3: "brown sugar",
      strIngredient4: "ground ginger",
      strIngredient5: "minced garlic",
      strIngredient6: "cornstarch",
      strIngredient7: "chicken breasts",
      strIngredient8: "stir-fry vegetables",
      strIngredient9: "brown rice",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: "3/4 cup",
      strMeasure2: "1/2 cup",
      strMeasure3: "1/4 cup",
      strMeasure4: "1/2 teaspoon",
      strMeasure5: "1/2 teaspoon",
      strMeasure6: "4 Tablespoons",
      strMeasure7: "2",
      strMeasure8: "1 (12 oz.)",
      strMeasure9: "3 cups",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "53052",
      strMeal: "Roti john",
      strDrinkAlternate: null,
      strCategory: "Beef",
      strArea: "Malaysian",
      strInstructions:
        "Mix all the ingredients in a bowl.\r\nHeat a pan or griddle with a little vegetable oil.\r\nPour the mixture onto the pan and place a piece of open-faced baguette on top.\r\nPress on the bread with a spatula and grill for 2 minutes.\r\nTurn the bread over to make it a little crispy.\r\nRemove from pan and cut the bread into small portions.\r\nAdd mayonnaise and/or Sambal before cutting the sandwich (optional).",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/hx335q1619789561.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=cl4YH8wblRs",
      strIngredient1: "Minced Beef",
      strIngredient2: "Onion",
      strIngredient3: "Eggs",
      strIngredient4: "Chilli",
      strIngredient5: "Baguette",
      strIngredient6: "Salt",
      strIngredient7: "Pepper",
      strIngredient8: "Mayonnaise",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1/4 lb",
      strMeasure2: "1",
      strMeasure3: "3",
      strMeasure4: "1 tbs",
      strMeasure5: "1/2 ",
      strMeasure6: "To taste",
      strMeasure7: "To taste",
      strMeasure8: "Top",
      strMeasure9: " ",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource: "https://www.196flavors.com/malaysia-roti-john/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52777",
      strMeal: "Mediterranean Pasta Salad",
      strDrinkAlternate: null,
      strCategory: "Seafood",
      strArea: "Italian",
      strInstructions:
        "Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
      strTags: "Pasta,Baking",
      strYoutube: "https://www.youtube.com/watch?v=e52IL8zYmaE",
      strIngredient1: "mozzarella balls",
      strIngredient2: "baby plum tomatoes",
      strIngredient3: "fresh basil",
      strIngredient4: "farfalle",
      strIngredient5: "extra virgin olive oil",
      strIngredient6: "Green Olives",
      strIngredient7: "tuna",
      strIngredient8: "salt",
      strIngredient9: "pepper",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: "200 g",
      strMeasure2: "250 g",
      strMeasure3: "1  bunch",
      strMeasure4: "350 g",
      strMeasure5: "3  tablespoons",
      strMeasure6: "40 g",
      strMeasure7: "200 g",
      strMeasure8: "to taste",
      strMeasure9: "to taste",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource:
        "https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52842",
      strMeal: "Broccoli & Stilton soup",
      strDrinkAlternate: null,
      strCategory: "Starter",
      strArea: "British",
      strInstructions:
        "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=_HgVLpmNxTY",
      strIngredient1: "Rapeseed Oil",
      strIngredient2: "Onion",
      strIngredient3: "Celery",
      strIngredient4: "Leek",
      strIngredient5: "Potatoes",
      strIngredient6: "Butter",
      strIngredient7: "Vegetable Stock",
      strIngredient8: "Broccoli",
      strIngredient9: "Stilton Cheese",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "2 tblsp ",
      strMeasure2: "1 finely chopped ",
      strMeasure3: "1",
      strMeasure4: "1 sliced",
      strMeasure5: "1 medium",
      strMeasure6: "1 knob",
      strMeasure7: "1 litre hot",
      strMeasure8: "1 Head chopped",
      strMeasure9: "140g",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource:
        "https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52804",
      strMeal: "Poutine",
      strDrinkAlternate: null,
      strCategory: "Miscellaneous",
      strArea: "Canadian",
      strInstructions:
        "Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\nWarm gravy in saucepan or microwave.\r\nPlace the fries into the hot oil, and cook until light brown, about 5 minutes.\r\nRemove to a paper towel lined plate to drain.\r\nPlace the fries on a serving platter, and sprinkle the cheese over them.\r\nLadle gravy over the fries and cheese, and serve immediately.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg",
      strTags: "UnHealthy,Speciality,HangoverFood",
      strYoutube: "https://www.youtube.com/watch?v=UVAMAoA2_WU",
      strIngredient1: "Vegetable Oil",
      strIngredient2: "Beef Gravy",
      strIngredient3: "Potatoes",
      strIngredient4: "Cheese Curds",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "Dash",
      strMeasure2: "1 Can",
      strMeasure3: "5 thin cut",
      strMeasure4: "2 cups",
      strMeasure5: "",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "http://www.food.com/recipe/real-canadian-poutine-113388",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52889",
      strMeal: "Summer Pudding",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "British",
      strInstructions:
        "Bring out the juices: Wash fruit and gently dry on kitchen paper – keep strawberries separate. Put sugar and 3 tbsp water into a large pan. Gently heat until sugar dissolves – stir a few times. Bring to a boil for 1 min, then tip in the fruit (not strawberries). Cook for 3 mins over a low heat, stirring 2-3 times. The fruit will be softened, mostly intact and surrounded by dark red juice. Put a sieve over a bowl and tip in the fruit and juice.\r\nLine the bowl with cling film and prepare the bread: Line the 1.25-litre basin with cling film as this will help you to turn out the pudding. Overlap two pieces of cling film in the middle of the bowl as it’s easier than trying to get one sheet to stick to all of the curves. Let the edges overhang by about 15cm. Cut the crusts off the bread. Cut 4 pieces of bread in half, a little on an angle, to give 2 lopsided rectangles per piece. Cut 2 slices into 4 triangles each and leave the final piece whole.\r\nBuild the pud: Dip the whole piece of bread into the juice for a few secs just to coat. Push this into the bottom of the basin. Now dip the wonky rectangular pieces one at a time and press around the basin’s sides so that they fit together neatly, alternately placing wide and narrow ends up. If you can’t quite fit the last piece of bread in it doesn’t matter, just trim into a triangle, dip in juice and slot in. Now spoon in the softened fruit, adding the strawberries here and there as you go.\r\nLet flavours mingle then serve: Dip the bread triangles in juice and place on top – trim off overhang with scissors. Keep leftover juice for later. Bring cling film up and loosely seal. Put a side plate on top and weight down with cans. Chill for 6 hrs or overnight. To serve, open out cling film then put a serving plate upside-down on top and flip over. serve with leftover juice, any extra berries and cream.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/rsqwus1511640214.jpg",
      strTags: "Summer",
      strYoutube: "https://www.youtube.com/watch?v=akJIO6UhXtA",
      strIngredient1: "Strawberries",
      strIngredient2: "Blackberries",
      strIngredient3: "Redcurrants",
      strIngredient4: "Raspberries",
      strIngredient5: "Caster Sugar",
      strIngredient6: "Bread",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "300g",
      strMeasure2: "250g",
      strMeasure3: "100g ",
      strMeasure4: "500g",
      strMeasure5: "175g",
      strMeasure6: "7 Slices",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/4516/summer-pudding",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52855",
      strMeal: "Banana Pancakes",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "American",
      strInstructions:
        "In a bowl, mash the banana with a fork until it resembles a thick purée. Stir in the eggs, baking powder and vanilla.\r\nHeat a large non-stick frying pan or pancake pan over a medium heat and brush with half the oil. Using half the batter, spoon two pancakes into the pan, cook for 1-2 mins each side, then tip onto a plate. Repeat the process with the remaining oil and batter. Top the pancakes with the pecans and raspberries.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg",
      strTags: "Breakfast,Desert,Sweet",
      strYoutube: "https://www.youtube.com/watch?v=kSKtb2Sv-_U",
      strIngredient1: "Banana",
      strIngredient2: "Eggs",
      strIngredient3: "Baking Powder",
      strIngredient4: "Vanilla Extract",
      strIngredient5: "Oil",
      strIngredient6: "Pecan Nuts",
      strIngredient7: "Raspberries",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 large",
      strMeasure2: "2 medium",
      strMeasure3: "pinch",
      strMeasure4: "spinkling",
      strMeasure5: "1 tsp ",
      strMeasure6: "25g",
      strMeasure7: "125g",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/banana-pancakes",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ]);

  const getRandomMeals = async () => {
    const randomMealsResponse = await get10RandomMeals();
    if (randomMealsResponse.success) {
      setRandomMeals(randomMealsResponse.data.meals);
    }
  };

  // useEffect(() => {
  //   getRandomMeals();
  // }, []);

  return (
    <div className="w-1/2">
      <p>Recipes</p>
      <div className="flex flex-col gap-2">
        {randomMeals.map((meal, mealId) => {
          const {
            idMeal,
            strMeal,
            strCategory,
            strMealThumb,
            strTags,
            strYoutube,
            strSource,
            strArea,
            strInstructions,
            ingredients,
          } = formatMealFromMealDB(meal);

          const tags = strTags?.split(",");
          const test = true;
          if (test) {
            return (
              <div className="indicator w-full">
                <div className="indicator-item indicator-bottom">
                  <button className="btn btn-primary">Apply</button>
                </div>
                <div className="card border w-full">
                  <div className="card-body">
                    <h2 className="card-title">{strMeal}</h2>
                    <p>{strCategory}</p>
                  </div>
                </div>
              </div>
            );
          }

          return (
            <div
              key={idMeal}
              className="card w-96 min-h-[200px] bg-neutral shadow-xl p-4"
            >
              <figure>
                <img
                  src={strMealThumb}
                  alt={strMeal}
                  className="w-full max-h-[200px] rounded-xl object-cover z-40"
                />
              </figure>
              <div className="card-body p-0 py-2">
                <h2 className="card-title">{strMeal}</h2>
                <span>{strCategory}</span>
                {tags && (
                  <div className="flex gap-1">
                    {tags.map((tag) => (
                      <div
                        key={`${mealId}-tag-${tag}`}
                        className="badge badge-secondary"
                      >
                        {tag}
                      </div>
                    ))}
                  </div>
                )}

                <div className="card-actions justify-end grow items-end">
                  <button className="btn btn-primary">View Recipe</button>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Recipes;
