export const build = {
  class: [
    "Assault Rifle",
    "Battle Rifle",
    "SMG",
    "Shotgun",
    "LMG",
    "Marksman Rifle",
    "Sniper",
    "Handgun",
  ],
  guns: {
    "Assault Rifle": [
      "Lachmann-556",
      "M4",
      "M16",
      "Kastov-74U",
      "TAQ-56",
      "STB 556",
      "Kastov 762",
      "Kastov 545",
      "M13B",
      "Chimera",
    ],
    "Battle Rifle": ["FTAC Recon", "Lachmann-762", "TAQ-V", "SO-14"],
    SMG: [
      "Lachmann Sub",
      "FSS Hurricane",
      "Fennec 45",
      "BAS-P",
      "MX9",
      "MINIBAK",
      "VEL 46",
      "PDSW-528",
      "Vaznek-9k",
    ],
    Shotgun: ["Expedite 12", "Bryson 800", "Bryson 890", "Lockwood 300"],
    LMG: ["556 Icarus", "RAPP H", "Sakin MG38", "RAAL MG", "HCR 56", "RPK"],
    "Marksman Rifle": [
      "LM-s",
      "Lockwood MK2",
      "SP-R 208",
      "EBR-14",
      "SA-B 50",
      "TAQ-M",
    ],
    Sniper: ["Signal 50", "LA-B 330", "MCPR-300", "SP-X 80", "Victus XMR"],
    Handgun: ["X12", "X13 Auto", "P890", ".50 GS", "Basilisk"],
  },
  attachments: {
    Barrels: [
      "15.5 Theta-X13", "LR:7 20.5 Barrel", "12 Tacshort Barrel", "11.5 T-H4 Barrel", "Tempus Trench Pro", "FTac SB", "419MM EXF Barrel", "17.5 Tundra Pro Barrel", "Lance-50 12 Barrel", "18 Precision-6 Barrel", "Hightower 20 Barrel", "FTac Coldforge 16 Barrel", "14 Carbine Shroud", "11.5 Carbine Shroud", "7.5 Tempus Firebrand", "Bull Rider 16.5", "FSS Cannonade 16", "FSS-X7 Barrel", "TAC 597 Barrel", "KAS-10 584mm Barrel", "KAS-7 406mm", "IG-K30 406mm", "342mm SAKIN KL", "SA Ultra III", "BR209 Barrel", "ShortTAC 330mm", "SA Response III", "KAS-1 381mm", "BAK-9 279mm Barrel", "15.9 Lachmann RAPP Barrel", "Meer-56 11 Factory", "LM Aurora 90 Barrel", "Lach-12 Barrel", "22.5 Elevate-11", "16 ZLR Executor 80 Barrel", "12.5 Carbon Barrel", "9 TAC-CB 55", "18.5 XRK Resonate", "23.5 Fluted R-67", "22 Cavalry Barrel", "FTac M-Sub 12”", "L38 Falcon 226mm", "Lachmann Pulsar", "10.6 Lachstrike Barrel", "Romeo FT 16 Barrel", "Lachmann Nova", "18 Demo Firewall", "Kastovia 343", "18 Bruen Guerilla", "24.4 Bruen S-620", "508MM Rear Guard", "Bruen Turaco 686mm", "FTac FB20", "Demo 501 Factory", "Kastovia 406", "16.5 Bruen S901", "Lachmann Dart 165mm", "Schlager RV-B", "Tango 228 Barrel", "Schlager L203 Barrel", "Lach-DX 203mm", "Lach-165 Zulu", "LM Series-7", "9.5 Duke-30", "Bryson Snubby", "FTAC Series IX 14.5", "16.5 STB Factory", "FTac Defense 14.5", "17 Corvus Prorange", "16 Cloak 90", "18.75 Cloak 90", "FTac 8.5 Recon", "Forge Tac Ninja", "Fennec Covert Force", "ZLR 16.5 Ignition Barrel", "5.5 Fennec Minitac", "22 Factory Fourteen Barrel", 
      "22 Boremaster Barrel", "18 T300 Barrel", "16 Chrome-Lined RFX40 Barrel", "KYZYL Dawn Barrel", "355mm HGS-55", "20 Bruen Silver Series Barrel", "FTac Hornet 20” Barrel", "EXF Gulf-16 Barrel", "21 EXF Rhino Barrel", "26.5 Demo Field Pro Barrel", "Meer-76 449mm Factory", "29.5 Rifled Barrel", "21.5” Bryson Shredder", "21.5 Recourse Barrel", "16 Bryson Shockwave", "16 Bryson Factory Barrel", "8 XRK CQB Barrel", "21.5 Recourse", "21.5 Bryson TacFire", "Matuzek 812 Barrel", "711mm Matuzek D50", "597mm Matuzek Inferno", "11 Bryson Special", "18.5 Emperor Barrel", "14 Polarize Barrel", "14 Shorty Barrel", "18.5 Battlemaster", "419mm Schlager Salvo", "22 OMX-456", "17.5 Orca Barrel", "19 Silentfire Barrel", "FSS Jetstream", "21.5 Fluted Fifty", "29 TV Kilo-50", "18.5 Bryson LR Factory", "Mack 8 33.5 Super", "SA Longshot-50", "Matuzek Cottonmouth Barrel", "XRK Luc-9", "FTAC Carnivora 7", "XRK Sidewinder-6 Slide", "10.5 Bruen Typhon", "Impact Point", "13.5 Lonestar Barrel", "6.5 EXF OP-40",
    ],
    Muzzles: [
      "TZL-90 V3", "ZLR Talon 5", "Echoline GS-X", "C400 Door Knocker", "Corvus Slash Gen. 2", "Echoless-80", "RF Crown 50", "GL Clear Breach", "Tempus GH50", "FTac Castle Comp", "FTac Dreadnought", "Shred CP90", "Demon Helix T7", "XTen Razor Comp", "XRK Knockout Breach", "Lockshot KT85", "Kastovia DX90", "TA Hul-Breach KL", "XTen Havoc 90", "VLK Koloss Flash Hider", "Gauge-9 Mono", "AVR-T90 Comp", "EXF Huntress-90", "Polarfire-S", "Komodo Heavy", "Broadhead-3DP", "ZULU-60", "SAKIN Tread-40", "Cronen OP44", "XTen Ported 290", "FSS Covert V", "Harbinger D20", "Silentfire XG6", "Dark KX30", "TY-LR8", "Ported DZ38", "Bruen Agent 90", "Nilsound 90", "XRK Kraken", "SA Schalldampfer 99", "Cronen Dark KX30", "Bryson Improved Choke", "Eight-Point Flash Hider", "Husher-65 Silencer", "Bore-490", "Talon Sixteen", "FSS VMW Flash Hider", "Spiral V3.5 Flash Hider", "XTen RR-40", "Forge DX90-F", "Singuard MKV", "XTen Black Kite", "Bruen Pendulum", "XRK Sandstorm", "Bruen Cubic Comp", "FOX-202 Flash Hider", "TA Hul-Breach", "Shikra Silencer", "EXF Relentless-40", "BVM-338", "Cronen DM338", "AP-390 Flash Hider", "Dark KX50 Flash Hider", "TA CG76", "FTac Reaper", "SA Schweigen DX", "SA Schweigen XS", "FTac Tridentcore", "SA MX-50", "RMGE-7", "Lockwood Smoothfire 12", "OVL-70 Comp", "Flash Twist-90", "XTen Quadflash", "Vulture Claw Breacher", "Mack8 Frost Bite", "XTen Full Choke", "XTen Modified Choke", "Bryson Choke", "Sakin DB107", "Tempus Vox", "GW Max-99", "DB-Big Bore Comp", "DB-Dread Comp", "Mack8 Shotgun Breach", "XTen V1.3 Choke", "XTen V2.0 Choke", "Bryson Series IX Choke", "Bryson Series XII Choke", "Reckoner Comp", "H26 Ported Comp", "Legion Fire Comp", "Demon Helix XL", "Bruen Counter-Ops", "Matuzek Crown", "FT Steel Fire", "FJX Fulcrum Pro", "Cronen Maw-86",
    ],
    Underbarrels: [
      "FSS Sharkfin 90", "VX Pineapple", "SPW 40mm", "Demo Imp-44 Grip", "Bruen Tilt Grip", "Hellscream 40mm", "Merc Foregrip", "Bipod V9 Grip", "RPK Bipod", "Schlager Tango", "KL40-M2", "Corvus Masterkey", "Edge-47 Grip", "Phase-3 Grip", "FTac Ripper 56", "Demo Firm Grip", "XTEN Gravedigger", "Level Aim Bipod", "Cornerstone Bipod", "XTen Stable Shot", "Demo Cleanshot 40", "Lockgrip Precision-40", "FTac Tiger Grip", "DI-Grip 4.5", "Hound-9G Grip", "B052 Grip", "Cronen Grooveshot Grip", "Agent Grip", "Bruen Sync Shot Grip", "XTEN Drop Grip", "Hex-40 Grip", "OP-X9 Foregrip", "Operator Foregrip", "TV Wrecker Grip", "Bruen Warrior Grip", "TL40 Fire Drake", "RAAL Bipod", "Sakin Side Grip", "Cronen WL55", "Bruen Warrior Grip (LMG)", "Soshki", "Bruen Heavy Bipod", "Demo Narrow Grip", "XRK Dune Grip", "SA Side Grip", "Commando Foregrip",
    ],
    Ammunition: [
      "6.5mm High Velocity", "6.5mm Hollowpoint", "6.5mm Frangible", "6.5mm Armor Piercing", "6.5mm Overpressured +P", "6.5mm Incendiary", "5.56 Armor Piercing", "5.56 Overpressured +P", ".458 Frangible", ".458 Overpressure +P", ".458 High Velocity", ".458 Hollow Point", ".458 Armor Piercing", "5.7x28mm Hollow Point", "7.62 Armor Piercing", "7.62 Incendiary", "5.56 High Velocity", "7.62 Hollowpoint", "7.62 Overpressured +P", "7.62 High Velocity", "7.62 Frangible", "5.45 Armor Piercing", "5.45 Overpressured +P", "5.45 High Velocity", "5.45 Hollowpoint", "5.45 Frangible", "9mm Hollowpoint", "9mm Frangible", "9mm Armor Piercing", "9mm Overpressured +P", "5.56 Frangible", ".308 Frangible", ".308 Armor Piercing", ".308 High Velocity", ".308 Overpressured +P", ".308 Hollow Point", ".308 Incendiary", ".300 Armor Piercing", ".45 GVT Frangible", ".45 GVT Hollowpoint", ".45 GVT Armor Piercing", ".45 GVT Overpressured +P", ".45 GVT High Velocity", ".45 GVT Incendiary", ".500 Hollowpoint", ".338 Mag Armor Piercing", ".500 Frangible", "5.7x28mm Armor Piercing", "4.6mm Frangible", "4.6mm Hollowpoint", "4.6mm Armor Piercing", "4.6mm Overpressured +P", "9mm Sub FR", "9mm Sub HP", "9mm Sub AP", "9mm Sub OP", "5.7x28mm Frangible", "5.7x28mm Overpressured +P", ".45 Auto Frangible", ".45 Auto Hollowpoint", ".45 Auto Armor Piercing", ".45 Auto Overpressured +P", "5.56 Incendiary", ".338 Mag Frangible", ".338 Mag Hollowpoint", ".338 Mag Overpressured +P", ".338 Mag High Velocity", ".338 Mag Incendiary", "12 Gauge Explosive", "12 Gauge Slug", "12 Gauge Dragon's Breath", ".300 Mag Armor Piercing", ".300 Mag Incendiary", ".300 Mag Frangible", ".300 Mag Hollowpoint", ".300 Mag High Velocity", ".300 Mag Overpressured +P", ".50 Cal Frangible", ".50 Cal Armor Piercing", ".50 Cal Explosive", ".300 Hollowpoint", ".300 Overpressured +P", ".300 High Velocity", ".300 Incendiary", ".300 Frangible", ".50 Cal High Velocity",
    ],
    Lasers: [
      "Corvus PEQ Beam-5", "Canted Vibro-Dot 7", "FTac Grimline Laser", "1MW Laser Box", "STOVL DR Laser Box", "SZ 1MW PEQ", "FJX Ultrabeam XR", "Schlager PEQ Box IV", "Corio LAZ-44 V3", "FSS OLE-V Laser", "Luminate-44", "DXS Flash 90", "1MW Quick Fire Laser", "Accu-Shot 5MW Laser", "VLK LZR 7MW", "Schlager Ulo-66 Laser", "STOVL Tac Laser", "Hipshot L20", "Point-G3P 04", "EXF Solarflare", "1MW Pistol Laser", "FJX Diod-70", "Corvus LZR-790", "Series 710 Pistol Laser", "1MW Artemis Laser",
    ],
    Optics: [
      "Cronen Mini Red Dot", "SZ Reflex", "XTEN Angel-40", "DXS Coriolis V4", "SZ Heatsource 800", "SZ Lonewolf Optic", "Cronen Zero-P Optic", "BPZ40 Hybrid", "Forge Tac Delta 4", "SZ SRO-7", "XRK On-Point Optic", "Drexsom Prime-90", "VX350 Thermal Optic", "VLK 4.0 Optic", "Kazan-Holo", "DF105 Reflex Sight", "Monocle CT90", "Hybrid Firepoint", "HMW-20 Optic", "Thermo-Optic X9", "SP-X 80 6.6x", "Teplo-OP3 Scope", "SZ Mini", "Schlager 4X", "Lachmann Impact 9", "Corio CQC Scope", "Slimline Pro", "Cronen Mini Pro", "SZ Sigma-IV Optic", "SZ Minitac-40", "Corvus SOL-76", "SZ Recharge-DX", "Corio RE-X Pro", "Corio Enforcer Optic", "Corvus Downrange-00", "SZ Holotherm", "SZ Bullseye Optic", "SZ Aggressor-IR Optic", "Schlager Night View", "DR582 Hybrid Sight", "SZ Vortex-90", "Angel-40 4.8x", "Teplo Clear Shot", "FTac Charlie7", "Luca Bandera Scope", "ARES Clear Shot", "Luca Canis 4x Optic", "Corio RV 500", "FTac Locus SP", "Daunt-C80", "Raptor-FVM40", "Cronen Irons", "Victus 13x", "Sightmax Clear Shot", "Signal 50 8x", "Corio 13X VRS", "MCPR-300 9.5x", "SZ Ultra 11.5x", "Aim Op-V4", "SZ Battle Optic", "Schlager 3.4x", "SZ Oscar-9", "DS Farsight 11", "3X RFL-Optic",
    ],
    Magazines: [
      "20 Round Mag", "40 Round Mag", "60 Round Mag", "30 Round Mag", "50 Round Drum", "45 Round Mag", "100 Round Box Mag", "15 Round Magazine", "5 Round Mag", "100 Round Drum", "Miniback Grip Mag", "10 Round Mag", "8-Round Magazine", "100 Round Mag", "Single Tap Mod", "42 Round Mag", "32 Round Mag", "Minibak Grip Mag", "Fennec Double Tap Mod", "Fennec Mag 45", "50 Round Mag", "25 Round Mag", "125 Round Belt Mag", "150-Round Box Magazine", "100 Round Belt Mag", "50 Round Belt Mag", "5-Shell Mag", "12 Shell Mag", "7 Round Magazine", "13 Round Mag", "24 Round Mag", "33 Round Mag",
    ],
    Stocks: [
      "Ravage-8", "Demo Fade Pro Stock", "Tempus P80 Strike Stock", "TV Ballast Stock", "TV XLINE Pro", "Corio Precio Factory", "Demo Precision Elite Factory", "TV Cardinal Stock", "TV LPX-434", "Tactique Brute Stock", "Demo D50 Buffer Tube", "Demo Quicksilver Collapsed", "Demo Quicksilver Stock", "Heavy Support Stock", "ProLite TL3 Stock", "KSTV-RPK Factory", "Ivanov Wood Stock", "Kastov-Rama", "FT TAC-Elite Stock", "VLK Stockless", "OTREZAT Stock", "Markeev R7 Stock", "Meer Recoil-56 Factory Stock", "LM-S Factory G79 Stock", "RAPP-762 Factory", "Lachmann S9 Factory", "ZRL T70 Pad Extension", "Bryson Inforcer Stock", "XRK Specter Mod", "FTAC EZX-Pro", "Assault-60 Stock Factory", "Bryson Streamline", "ZLR T70 Pad Extension", "PVZ-890 Tac Stock", "LM Stockless Mod", "FT Mobile Stock", "FTAC Apollo Stock", "Lachmann S76 Factory Stock", "Bruen MX9 Stock", "Bruen HCR 56 Stock", "Spetsnaz S10 Stock", "Cut Off Stock Mod", "Demo VX509 Stock", "Lockwood Bullseye Stock", "Assault-60 Stock", "Demo RXT Stock", "LM Precision Stock", "VEL A-568 Collapsed", "Demo H-40", "CQB Stock", "FSS Heavy Stock Pro", "Bruen STB 556 Stock", "Guard Duty Stock", "Fennec Bullfighter", "FTac XCommand Stock", "FTac Locktight Stock", "Agile Assault-7 Stock", "FTac Stock Cap", "FTac RTP-40 Stock", "SO R55 Adaptor", "Model 1957 Stock", "Sakin Riptide Stock", "FTac Condor Stock", "Cheetah STM Stock", "Demo Nimble Stock", "FSS Riot Stock", "Demo Folding Stock", "FSS Guardian Stock", "FSS Watchman", "XTen Ripcord Stock", "Stockless Pistol Grip", "Sawed Off Mod", "Bryson 800 Factory Stock", "Sweetspot Stock", "Cronen Marshal Stock", "Bryson Natural Series Stock", "Heist Stock Mod", "Resonance Stock Collapsed", "FSS Frame Stock", "Bryson Reverb-55 Stock", "Schlager Resonance", "Cronen Lion Stock", "Cronen LW-88 Stock", "FSS Merc Stock", "FSS Echo Stock", "SO Inline Stock", "FTac Invisi-670 Stock", "Max DMR Precision", "EXF Colonel", "FTac Valor Stock", "Hollow Extended Stock", "XRK Bar Stock",
    ],
    "Rear Grips": [
      "D15 Grip","Sakin ZX Grip","XTEN Grip",
      "Phantom Grip","TV Ergo Grip","XRK Response Grip",
      "Support CP90 Grip","FSS Combat Grip","Demo Cleanshot Grip",
      "Demo-X2 Grip","Ivanov ST-70 Grip","True-TAC Grip",
      "S-Grip Zero","Bruen Lynx Grip","Cronen Grip Wrap",
      "LM Cronus Grip","LMK64 Grip","Bruen G305 Grip Wrap",
      "STIP-40 Grip","Bruen Q900 Grip","Lachmann TCG-10",
      "Sakin Rubber Grip","ZLR Combat Grip","Schlager Soldier Grip",
      "Fennec Stippled Grip","Fennec Textured Grip","Fennec Rubber Grip",
      "Goliath 77 Grip","Schlager Fang Grip","Schlager Void Grip",
      "Cronen Zero Grip","Cronen RFX-300","Cronen Cheetah Grip",
      "Stalwart Grip","Cronen Blockade Grip","SA Finesse Grip",
      "Schlager Match Grip","EXF Resistance Grip","Bruen RSH-80 Grip",
      "XRK Field Grip","Bryson WD-85 Grip","Bruen Flash Grip",
      "FTac OL-Z Grip","D37 Grip",
    ],
  },
};
