export const build = {
  class: [
    "Assault Rifle",
    "Battle Rifle",
    "SMG",
    "Shotgun",
    "LMG",
    "Marksman Rifle",
    "Sniper",
    "Handgun",
  ],
  guns: {
    "Assault Rifle": [
      "Lachmann-556",
      "M4",
      "M16",
      "Kastov-74U",
      "TAQ-56",
      "STB 556",
      "Kastov 762",
      "Kastov 545",
      "M13B",
      "Chimera",
    ],
    "Battle Rifle": ["FTAC Recon", "Lachmann-762", "TAQ-V", "SO-14"],
    SMG: [
      "Lachmann Sub",
      "FSS Hurricane",
      "Fennec 45",
      "BAS-P",
      "MX9",
      "MINIBAK",
      "VEL 46",
      "PDSW-528",
      "Vaznek-9k",
    ],
    Shotgun: ["Expedite 12", "Bryson 800", "Bryson 890", "Lockwood 300"],
    LMG: ["556 Icarus", "RAPP H", "Sakin MG38", "RAAL MG", "HCR 56", "RPK"],
    "Marksman Rifle": [
      "LM-s",
      "Lockwood MK2",
      "SP-R 208",
      "EBR-14",
      "SA-B 50",
      "TAQ-M",
    ],
    Sniper: ["Signal 50", "LA-B 330", "MCPR-300", "SP-X 80", "Victus XMR"],
    Handgun: ["X12", "X13 Auto", "P890", ".50 GS", "Basilisk"],
  },
  attachments: {
    Barrels: [
      "10.5 Bruen Typhon",
      "10.5 FTac Arrow",
      "10.6 Lachstrike Barrel",
      "11.5 Carbine Shroud",
      "11.5 T-H4 Barrel",
      "11 Bryson Special",
      "12.5 Carbon Barrel",
      "12 Bruen SZ-36",
      "12 TacShort Barrel",
      "13.5 Lonestar Barrel",
      "14.5 Tundra Pro Barrel",
      "14 Bruen Echelon",
      "14 Carbine Shroud",
      "14 Polarize Barrel",
      "14 Shorty Barrel",
      "15.5 Theta-X13",
      "15.9 Lachmann RAPP Barrel",
      "16.5 Bruen S901 Barrel",
      "16 Bryson Factory Barrel",
      "16 Bryson Shockwave",
      "16 Chrome-Lined RFX40",
      "16 Cloak 90",
      "16 ZLR Executor 80 Barrel",
      "17.5 Orca Barrel",
      "17 Corvus Prorange",
      "18.5 Battlemaster",
      "18.5 Bryson LR Factory",
      "18.5 Emperor Barrel",
      "18.5 XRK Resonate",
      "18.75 Cloak 90",
      "18 Bruen Guerilla",
      "18 Demo Firewall",
      "18 Precision-6 Barrel",
      "18 T300",
      "19 Silentfire Barrel",
      "20 Bruen Silver Series",
      "21.5 Bryson Shredder",
      "21.5 Bryson TacFire",
      "21.5 Fluted Fifty",
      "21.5 Recourse",
      "21 Coyote Barrel",
      "21 EXF Rhino",
      "22.5 Elevate-11",
      "22.5 EXF Alamo",
      "22 Boremaster",
      "22 Cavalry Barrel",
      "22 Factory Fourteen",
      "22 OMX-456",
      "23.5 Fluted R-67",
      "24.4 Bruen S-620",
      "25 Buffalo Barrel",
      "26.5 Demo Field Pro",
      "26 Mammoth HB50",
      "29.5 Rifled Barrel",
      "29 TV Kilo-50",
      "342mm SAKIN KL",
      "355mm HGS-55",
      "4 Thunderfire",
      "419mm EXF Barrel",
      "419mm Schlager Salvo",
      "5.5 Fennec Minitac",
      "508mm Rear Guard",
      "597mm Matuzek Inferno",
      "6.5 Bruen Drake",
      "6.75 Corvus Cougar 500",
      "7.5 Tempus Firebrand",
      "7 Bruen B-M20",
      "711mm Matuzek D50",
      "8 XRK CQB Barrel",
      "9.5 Duke-30",
      "9 Tac-CB 55",
      "BAK-9 279mm Barrel",
      "BR209 Barrel",
      "Bruen Turaco 686mm",
      "Bryson Snubby",
      "Bull Rider 16.5",
      "Demo 501 Factory",
      "Executor 546",
      "EXF Gulf-16 Barrel",
      "Fennec Covert Force",
      "Forge Tac Ninja",
      "FSS Cannonade 16",
      "FSS Jetstream",
      "FSS-X7 Barrel",
      "FTac 8.5 Recon",
      "FTac Carnivora 7",
      "FTac Coldforge 16 Barrel",
      "FTac Defense 14.5",
      "FTac Fang Ported",
      "FTac FB20",
      "FTac Hornet 20 Barrel",
    ],
    Muzzles: [
      "TZL-90 V3",
      "ZLR Talon 5",
      "Echoline GS-X",
      "C400 Door Knocker",
      "Corvus Slash Gen. 2",
      "Echoless-80",
      "RF Crown 50",
      "GL Clear Breach",
      "Tempus GH50",
      "FTac Castle Comp",
      "FTac Dreadnought",
      "Shred CP90",
      "Demon Helix T7",
      "XTen Razor Comp",
      "XRK Knockout Breach",
      "Lockshot KT85",
      "Kastovia DX90",
      "TA Hul-Breach KL",
      "XTen Havoc 90",
      "VLK Koloss Flash Hider",
      "Gauge-9 Mono",
      "AVR-T90 Comp",
      "EXF Huntress-90",
      "Polarfire-S",
      "Komodo Heavy",
      "Broadhead-3DP",
      "ZULU-60",
      "SAKIN Tread-40",
      "Cronen OP44",
      "XTen Ported 290",
      "FSS Covert V",
      "Harbinger D20",
      "Silentfire XG6",
      "Dark KX30",
      "TY-LR8",
      "Ported DZ38",
      "Bruen Agent 90",
      "Nilsound 90",
      "XRK Kraken",
      "SA Schalldampfer 99",
      "Cronen Dark KX30",
      "Bryson Improved Choke",
      "Eight-Point Flash Hider",
      "Husher-65 Silencer",
      "Bore-490",
      "Talon Sixteen",
      "FSS VMW Flash Hider",
      "Spiral V3.5 Flash Hider",
      "XTen RR-40",
      "Forge DX90-F",
      "Singuard MKV",
      "XTen Black Kite",
      "Bruen Pendulum",
      "XRK Sandstorm",
      "Bruen Cubic Comp",
      "FOX-202 Flash Hider",
      "TA Hul-Breach",
      "Shikra Silencer",
    ],
    Underbarrels: [
      "FSS Sharkfin 90",
      "VX Pineapple",
      "SPW 40mm",
      "Demo Imp-44 Grip",
      "Bruen Tilt Grip",
      "Hellscream 40mm",
      "Merc Foregrip",
      "Bipod V9 Grip",
      "RPK Bipod",
      "Schlager Tango",
      "KL40-M2",
      "Corvus Masterkey",
      "Edge-47 Grip",
      "Phase-3 Grip",
      "FTac Ripper 56",
      "Demo Firm Grip",
      "XTEN Gravedigger",
      "Level Aim Bipod",
      "Cornerstone Bipod",
      "XTen Stable Shot",
      "Demo Cleanshot 40",
      "Lockgrip Precision-40",
      "FTac Tiger GripDI-Grip 4.5",
      "Hound-9G Grip",
      "B052 Grip",
      "Cronen Grooveshot Grip",
      "Agent Grip",
      "Bruen Sync Shot Grip",
      "XTEN Drop Grip",
      "Hex-40 Grip",
      "OP-X9 Foregrip",
      "Operator Foregrip",
      "TV Wrecker Grip",
      "Bruen Warrior Grip",
      "TL40 Fire Drake",
      "RAAL Bipod",
    ],
    Ammunition: [
      "6.5mm High Velocity",
      "6.5mm Hollowpoint",
      "6.5mm Frangible",
      "6.5mm Armor Piercing",
      "6.5mm Overpressured +P",
      "6.5mm Incendiary",
      "5.56 Armor Piercing",
      "5.56 Overpressured +P",
      ".458 Frangible",
      ".458 Overpressure +P",
      ".458 High Velocity",
      ".458 Hollow Point",
      ".458 Armor Piercing",
      "5.7x28mm Hollow Point",
      "7.62 Armor Piercing",
      "7.62 Incendiary",
      "5.56 High Velocity",
      "7.62 Hollowpoint",
      "7.62 Overpressured +P",
      "7.62 High Velocity",
      "7.62 Frangible",
      "5.45 Armor Piercing",
      "5.45 Overpressured +P",
      "5.45 High Velocity",
      "5.45 Hollowpoint",
      "5.45 Frangible",
      "9mm Hollowpoint",
      "9mm Frangible",
      "9mm Armor Piercing",
      "9mm Overpressured +P",
      "5.56 Frangible",
      ".308 Frangible",
      ".308 Armor Piercing",
      ".308 High Velocity",
      ".308 Overpressured +P",
      ".308 Hollow Point",
      ".308 Incendiary",
      ".300 Armor Piercing",
      ".45 GVT Frangible",
      ".45 GVT Hollowpoint",
      ".45 GVT Armor Piercing",
      ".45 GVT Overpressured +P",
      ".45 GVT High Velocity",
      ".45 GVT Incendiary",
      ".500 Hollowpoint",
      ".338 Mag Armor Piercing",
      ".500 Frangible",
      "5.7x28mm Armor Piercing",
      "4.6mm Frangible",
      "4.6mm Hollowpoint",
      "4.6mm Armor Piercing",
      "4.6mm Overpressured +P",
      "9mm Sub FR",
      "9mm Sub HP",
      "9mm Sub AP",
      "9mm Sub OP",
      "5.7x28mm Frangible",
      "5.7x28mm Overpressured +P",
      ".45 Auto Frangible",
      ".45 Auto Hollowpoint",
      ".45 Auto Armor Piercing",
      ".45 Auto Overpressured +P",
    ],
    Lasers: [
      "Corvus PEQ Beam-5",
      "Canted Vibro-Dot 7",
      "FTac Grimline Laser",
      "1MW Laser Box",
      "STOVL DR Laser Box",
      "SZ 1MW PEQ",
      "FJX Ultrabeam XR",
      "Schlager PEQ Box IV",
      "Corio LAZ-44 V3",
      "FSS OLE-V Laser",
      "Luminate-44",
      "DXS Flash 90",
      "1MW Quick Fire Laser",
      "Accu-Shot 5MW Laser",
      "VLK LZR 7MW",
      "Schlager Ulo-66 Laser",
      "STOVL Tac Laser",
      "Hipshot L20",
      "Point-G3P 04",
      "EXF Solarflare",
    ],
    Optics: [
      "XTEN Angel-40",
      "SZ Lonewolf Optic",
      "Cronen Zero-P Optic",
      "BPZ40 Hybrid",
      "Forge Tac Delta 4",
      "SZ SRO-7",
      "VLK 4.0 Optic",
      "DF105 Reflex Sight",
      "Hybrid Firepoint",
      "Thermo-Optic X9",
      "SZ Mini",
      "Schlager 4X",
      "Slimline Pro",
      "SZ Minitac-40",
      "Corvus SOL-76",
      "SZ Recharge-DX",
      "Corio Enforcer Optic",
      "Corvus Downrange-00",
      "SZ Bullseye Optic",
      "DR582 Hybrid Sight",
      "Angel-40 4.8x",
      "Teplo Clear Shot",
      "FTac Charlie7",
      "ARES Clear Shot",
      "Raptor-FVM40",
      "Cronen Mini Red Dot",
      "XRK On-Point Optic",
      "Kazan-Holo",
      "Monocle CT90",
      "SZ Vortex-90",
      "SZ Heatsource 800",
      "Cronen Mini Pro",
      "Corio RE-X Pro",
      "SZ Sigma-IV Optic",
      "SZ Holotherm",
      "Schlager Night View",
      "DXS Coriolis V4",
      "VX350 Thermal Optic",
      "HMW-20 Optic",
      "SP-X 80 6.6x",
      "Lachmann Impact 9",
      "Corio CQC Scope",
      "Luca Bandera Scope",
      "Luca Canis 4x Optic",
      "Drexsom Prime-90",
      "Teplo-OP3 Scope",
      "SZ Aggressor-IR Optic",
    ],
    Magazines: [
      "40 Round Mag",
      "60 Round Mag",
      "30 Round Mag",
      "50 Round Drum",
      "45 Round Mag",
      "100 Round Box Mag",
      "15 Round Magazine",
      "5 Round Mag",
      "100 Round Drum",
      "Miniback Grip Mag",
      "10 Round Mag",
      "8-Round Magazine",
      "100 Round Mag",
      "Single Tap Mod",
      "42 Round Mag",
      "32 Round Mag",
      "Minibak Grip Mag",
      "Fennec Double Tap Mod",
      "Fennec Mag 45",
      "50 Round Mag",
    ],
    Stocks: [
      "Ravage-8",
      "Demo Fade Pro Stock",
      "Tempus P80 Strike Stock",
      "TV Ballast Stock",
      "TV XLINE Pro",
      "Corio Precio Factory",
      "Demo Precision Elite Factory",
      "TV Cardinal Stock",
      "TV LPX-434",
      "Tactique Brute Stock",
      "Demo D50 Buffer Tube",
      "Demo Quicksilver Collapsed",
      "Demo Quicksilver Stock",
      "Heavy Support Stock",
      "ProLite TL3 Stock",
      "KSTV-RPK Factory",
      "Ivanov Wood Stock",
      "Kastov-Rama",
      "FT TAC-Elite Stock",
      "VLK Stockless",
      "OTREZAT Stock",
      "Markeev R7 Stock",
      "Meer Recoil-56 Factory Stock",
      "LM-S Factory G79 Stock",
      "RAPP-762 Factory",
      "Lachmann S9 Factory",
      "ZRL T70 Pad Extension",
      "Bryson Inforcer Stock",
      "XRK Specter Mod",
      "FTAC EZX-Pro",
      "Assault-60 Stock Factory",
      "Bryson Streamline",
      "ZLR T70 Pad Extension",
      "PVZ-890 Tac Stock",
      "LM Stockless Mod",
      "FT Mobile Stock",
      "FTAC Apollo Stock",
      "Lachmann S76 Factory Stock",
      "Bruen MX9 Stock",
      "Bruen HCR 56 Stock",
      "Spetsnaz S10 Stock",
      "Cut Off Stock Mod",
      "Demo VX509 Stock",
      "Lockwood Bullseye Stock",
      "Assault-60 Stock",
      "Demo RXT Stock",
      "LM Precision Stock",
      "VEL A-568 Collapsed",
      "Demo H-40",
      "CQB Stock",
      "FSS Heavy Stock Pro",
      "Bruen STB 556 Stock",
      "Guard Duty Stock",
      "Fennec Bullfighter",
      "FTac XCommand Stock",
      "FTac Locktight Stock",
      "Agile Assault-7 Stock",
      "FTac Stock Cap",
    ],
    "Rear Grips": [
      "D15 Grip",
      "Sakin ZX Grip",
      "XTEN Grip",
      "Phantom Grip",
      "TV Ergo Grip",
      "XRK Response Grip",
      "Support CP90 Grip",
      "FSS Combat Grip",
      "Demo Cleanshot Grip",
      "Demo-X2 Grip",
      "Ivanov ST-70 Grip",
      "True-TAC Grip",
      "S-Grip Zero",
      "Bruen Lynx Grip",
      "Cronen Grip Wrap",
      "LM Cronus Grip",
      "LMK64 Grip",
      "Bruen G305 Grip Wrap",
      "STIP-40 Grip",
      "Bruen Q900 Grip",
      "Lachmann TCG-10",
      "Sakin Rubber Grip",
      "ZLR Combat Grip",
      "Schlager Soldier Grip",
      "Fennec Stippled Grip",
      "Fennec Textured Grip",
      "Fennec Rubber Grip",
    ],
  },
};
